version: 2.1

# Variables
executors:
  linux:
    docker:
      - image: cimg/node:12.20-browsers
commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - nrwl-nx-yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          # Windows needs its own cache key because binaries in node_modules are different.
          key: nrwl-nx-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  noop:
    executor: linux
    steps:
      - setup
      - run:
          name: Run Unit Tests
          command: echo noop
workflows:
  build:
    jobs:
      - noop
