version: 2.1

# Variables
executors:
  linux:
    docker:
      - image: cimg/node:12.20-browsers
jobs:
  noop:
    executor: linux
    steps:
      - run:
          name: noop
          command: echo noop
workflows:
  build:
    jobs:
      - noop
