name: CI Checks
on: [push, pull_request]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
  lint:
    runs-on: ${{ matrix.os }}
    
    env:
      NX_BRANCH: ${{ github.event.number || github.ref }}
      NX_RUN_GROUP: ${{ github.run_id }}
      
    needs: [setup]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - run: yarn nx run-many --all --parallel --target=lint

  build:
    runs-on: ${{ matrix.os }}
    
    env:
      NX_BRANCH: ${{ github.event.number || github.ref }}
      NX_RUN_GROUP: ${{ github.run_id }}
      
    needs: [setup]

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - run: yarn nx run-many --all --parallel --target=build

  test:
    runs-on: ${{ matrix.os }}

    env:
      NX_BRANCH: ${{ github.event.number || github.ref }}
      NX_RUN_GROUP: ${{ github.run_id }}
      
    needs: [setup]

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - run: yarn nx run-many --all --parallel --target=test
